import { getServerSession } from "next-auth";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {  

  return (
    <html lang="en" data-theme="winter">
     
      <body className={inter.className}>
        <div className="navbar bg-base-300">
          <div className="flex-1">
            <Link className="btn btn-ghost text-xl" href="/">
              daisyUI
            </Link>
          </div>
          <div className="flex-none">
            <ul className="menu menu-horizontal px-1">
              <li>
                <Link href="/users">Users</Link>
              </li>
              <li>
                <details>
                  <summary>Parent</summary>
                  <ul className="p-2 bg-base-100 rounded-t-none">
                    <li>
                      <a>Link 1</a>
                    </li>
                    <li>
                      <a>Link 2</a>
                    </li>
                  </ul>
                </details>
              </li>
            </ul>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
